'use client';

import { useState, useRef } from 'react';

const PAGE_OPTIONS = [10, 15, 20, 25, 30, 40, 50];

const TOPIC_SUGGESTIONS = [
  'Dinosaurs', 'Space & Planets', 'Ocean Animals',
  'Enchanted Forest', 'Farm Animals', 'Superheroes',
  'Princess Castle', 'Jungle Safari', 'Robots',
  'Underwater World', 'Magical Unicorns', 'Vehicles & Cars',
];

// Estimated time per page in seconds (DALL-E 3 ~10–15s per image)
const SECONDS_PER_PAGE = 13;

export default function GeneratorForm() {
  const [topic, setTopic] = useState('');
  const [pageCount, setPageCount] = useState(20);
  const [status, setStatus] = useState('idle'); // idle | generating | success | error
  const [error, setError] = useState('');
  const [progress, setProgress] = useState(0);
  const [pdfUrl, setPdfUrl] = useState(null);
  const [pdfFilename, setPdfFilename] = useState('');
  const [topicError, setTopicError] = useState('');
  const downloadRef = useRef(null);
  const timerRef = useRef(null);

  // ── Validation ────────────────────────────────────────────────────────────
  function validateTopic(val) {
    if (!val.trim()) return 'Please enter a topic.';
    if (val.trim().length < 2) return 'Topic must be at least 2 characters.';
    if (val.trim().length > 100) return 'Topic must be 100 characters or fewer.';
    if (!/^[a-zA-Z0-9 ,.'-]+$/.test(val.trim()))
      return 'Use letters, numbers, spaces and basic punctuation only.';
    return '';
  }

  function handleTopicChange(e) {
    setTopic(e.target.value);
    if (topicError) setTopicError(validateTopic(e.target.value));
  }

  function handleTopicBlur() {
    setTopicError(validateTopic(topic));
  }

  // ── Progress simulation ───────────────────────────────────────────────────
  function startProgressSimulation(total) {
    setProgress(0);
    const totalMs = total * SECONDS_PER_PAGE * 1000;
    const intervalMs = 400;
    const increment = (intervalMs / totalMs) * 90; // go up to 90%, API sets 100%
    timerRef.current = setInterval(() => {
      setProgress((prev) => Math.min(prev + increment, 90));
    }, intervalMs);
  }

  function stopProgressSimulation() {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  }

  // ── Submit ────────────────────────────────────────────────────────────────
  async function handleSubmit(e) {
    e.preventDefault();

    const err = validateTopic(topic);
    if (err) { setTopicError(err); return; }

    // Revoke previous object URL
    if (pdfUrl) { URL.revokeObjectURL(pdfUrl); setPdfUrl(null); }

    setStatus('generating');
    setError('');
    setProgress(0);
    startProgressSimulation(pageCount);

    try {
      const res = await fetch('/api/generate-book', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: topic.trim(), pageCount }),
      });

      stopProgressSimulation();

      if (!res.ok) {
        let msg = 'Something went wrong. Please try again.';
        try {
          const data = await res.json();
          msg = data.error || (data.errors && data.errors.join(' ')) || msg;
        } catch {}
        throw new Error(msg);
      }

      setProgress(100);

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const filename =
        `bookmint-${topic.trim().replace(/\s+/g, '-').toLowerCase()}-coloring-book.pdf`;

      setPdfUrl(url);
      setPdfFilename(filename);
      setStatus('success');

      // Auto-trigger download
      setTimeout(() => {
        if (downloadRef.current) downloadRef.current.click();
      }, 300);
    } catch (err) {
      stopProgressSimulation();
      setError(err.message || 'An unexpected error occurred.');
      setStatus('error');
      setProgress(0);
    }
  }

  function handleReset() {
    if (pdfUrl) URL.revokeObjectURL(pdfUrl);
    setPdfUrl(null);
    setPdfFilename('');
    setStatus('idle');
    setError('');
    setProgress(0);
    setTopic('');
    setPageCount(20);
  }

  const isGenerating = status === 'generating';
  const estimatedMinutes = Math.ceil((pageCount * SECONDS_PER_PAGE) / 60);

  return (
    <div className="w-full max-w-2xl mx-auto">
      {/* ── Card ── */}
      <div className="card-paper p-8 md:p-12">

        {/* Header */}
        <div className="mb-8 text-center">
          <span className="section-label">AI Generator</span>
          <h2
            className="font-display text-2xl md:text-3xl text-ink-900 mt-2"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Create Your Coloring Book
          </h2>
          <p className="text-ink-500 text-sm mt-2 font-body">
            Each book is uniquely generated by AI — no two are alike.
          </p>
        </div>

        {status === 'success' ? (
          <SuccessState
            topic={topic}
            pageCount={pageCount}
            pdfUrl={pdfUrl}
            pdfFilename={pdfFilename}
            downloadRef={downloadRef}
            onReset={handleReset}
          />
        ) : (
          <form onSubmit={handleSubmit} noValidate>

            {/* Topic input */}
            <div className="mb-6">
              <label
                htmlFor="topic"
                className="block text-sm font-body font-medium text-ink-700 mb-2"
              >
                Topic <span className="text-rust">*</span>
              </label>
              <input
                id="topic"
                type="text"
                className={`input-field ${topicError ? 'border-rust' : ''}`}
                placeholder="e.g. Dinosaurs, Space, Ocean Animals…"
                value={topic}
                onChange={handleTopicChange}
                onBlur={handleTopicBlur}
                disabled={isGenerating}
                maxLength={100}
                autoComplete="off"
                autoFocus
              />
              {topicError && (
                <p className="mt-1.5 text-xs text-rust font-body">{topicError}</p>
              )}

              {/* Topic suggestions */}
              <div className="flex flex-wrap gap-2 mt-3">
                {TOPIC_SUGGESTIONS.map((s) => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => { setTopic(s); setTopicError(''); }}
                    disabled={isGenerating}
                    className="px-3 py-1 text-xs font-body border border-ink-200 text-ink-600
                               hover:border-ink-900 hover:text-ink-900 hover:bg-parchment
                               transition-all duration-150 disabled:opacity-40 disabled:cursor-not-allowed"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>

            {/* Page count */}
            <div className="mb-8">
              <label className="block text-sm font-body font-medium text-ink-700 mb-3">
                Number of Pages
                <span className="ml-2 text-rust font-semibold">{pageCount}</span>
              </label>

              {/* Slider */}
              <div className="relative">
                <input
                  type="range"
                  min="10"
                  max="50"
                  step="5"
                  value={pageCount}
                  onChange={(e) => setPageCount(Number(e.target.value))}
                  disabled={isGenerating}
                  className="w-full h-1.5 bg-ink-200 rounded-none appearance-none cursor-pointer
                             accent-ink-900 disabled:opacity-40 disabled:cursor-not-allowed"
                />
                <div className="flex justify-between mt-2">
                  {PAGE_OPTIONS.map((n) => (
                    <button
                      key={n}
                      type="button"
                      onClick={() => setPageCount(n)}
                      disabled={isGenerating}
                      className={`text-xs font-body px-1.5 py-0.5 transition-all duration-100
                        ${pageCount === n
                          ? 'text-ink-900 font-semibold'
                          : 'text-ink-400 hover:text-ink-700'}
                        disabled:opacity-40 disabled:cursor-not-allowed`}
                    >
                      {n}
                    </button>
                  ))}
                </div>
              </div>

              <p className="text-xs text-ink-400 font-body mt-2">
                Est. generation time: ~{estimatedMinutes} min
              </p>
            </div>

            {/* Error banner */}
            {status === 'error' && error && (
              <div className="mb-6 px-4 py-3 bg-rust/10 border border-rust/30 text-rust text-sm font-body">
                <strong className="font-semibold">Error: </strong>{error}
              </div>
            )}

            {/* Progress */}
            {isGenerating && (
              <GeneratingState progress={progress} pageCount={pageCount} topic={topic} />
            )}

            {/* Submit */}
            {!isGenerating && (
              <button
                type="submit"
                className="btn-primary w-full text-base"
                disabled={isGenerating}
              >
                <BookIcon />
                Generate Coloring Book
              </button>
            )}
          </form>
        )}
      </div>

      {/* Fine print */}
      {status === 'idle' || status === 'error' ? (
        <p className="text-center text-xs text-ink-400 font-body mt-4">
          Images are generated with DALL·E 3. Generation takes 2–10 minutes depending on page count.
        </p>
      ) : null}
    </div>
  );
}

// ─── Sub-components ──────────────────────────────────────────────────────────

function GeneratingState({ progress, pageCount, topic }) {
  return (
    <div className="py-4">
      {/* Animated book icon */}
      <div className="flex justify-center mb-6">
        <div className="relative w-16 h-16 flex items-center justify-center">
          <div className="w-12 h-12 border-2 border-ink-200 flex items-center justify-center">
            <div className="page-turn">
              <PageIcon />
            </div>
          </div>
        </div>
      </div>

      <p className="text-center font-body font-medium text-ink-800 mb-1">
        Crafting your{' '}
        <em className="font-display not-italic text-rust">{topic}</em> coloring book…
      </p>
      <p className="text-center text-xs text-ink-500 font-body mb-5">
        Generating {pageCount} unique AI illustrations. Please keep this tab open.
      </p>

      {/* Progress bar */}
      <div className="w-full bg-ink-100 h-1.5 overflow-hidden">
        <div
          className="h-full progress-bar transition-all duration-500 ease-out"
          style={{ width: `${progress}%` }}
        />
      </div>
      <div className="flex justify-between mt-1.5">
        <span className="text-xs text-ink-400 font-body">Drawing pages…</span>
        <span className="text-xs text-ink-600 font-body font-medium">
          {Math.round(progress)}%
        </span>
      </div>

      {/* Skeleton pages preview */}
      <div className="mt-6 grid grid-cols-5 gap-2">
        {Array.from({ length: Math.min(pageCount, 10) }).map((_, i) => (
          <div
            key={i}
            className={`aspect-[3/4] ${
              i < Math.floor((progress / 100) * Math.min(pageCount, 10))
                ? 'bg-forest/20 border border-forest/30'
                : 'shimmer-bg border border-ink-100'
            } transition-all duration-300`}
          />
        ))}
      </div>
      {pageCount > 10 && (
        <p className="text-center text-xs text-ink-400 font-body mt-2">
          +{pageCount - 10} more pages
        </p>
      )}
    </div>
  );
}

function SuccessState({ topic, pageCount, pdfUrl, pdfFilename, downloadRef, onReset }) {
  return (
    <div className="text-center py-4 animate-fade-up">
      {/* Check icon */}
      <div className="flex justify-center mb-5">
        <div className="w-16 h-16 border-2 border-forest flex items-center justify-center">
          <svg className="w-8 h-8 text-forest" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="square" strokeLinejoin="miter" d="M5 13l4 4L19 7" />
          </svg>
        </div>
      </div>

      <h3 className="font-display text-2xl text-ink-900 mb-2" style={{ fontFamily: 'var(--font-display)' }}>
        Your book is ready!
      </h3>
      <p className="text-ink-500 font-body text-sm mb-2">
        <strong className="text-ink-800">{pageCount} pages</strong> about{' '}
        <em className="font-display not-italic text-rust">{topic}</em>
      </p>
      <p className="text-ink-400 font-body text-xs mb-8">
        Your download should start automatically. If not, click below.
      </p>

      {/* Hidden auto-download link */}
      <a
        ref={downloadRef}
        href={pdfUrl}
        download={pdfFilename}
        className="hidden"
        aria-hidden="true"
      />

      {/* Manual download button */}
      <a
        href={pdfUrl}
        download={pdfFilename}
        className="btn-primary inline-flex mb-4 w-full justify-center"
      >
        <DownloadIcon />
        Download PDF
      </a>

      <button
        type="button"
        onClick={onReset}
        className="btn-secondary w-full"
      >
        Generate Another Book
      </button>
    </div>
  );
}

// ─── Tiny inline icons ────────────────────────────────────────────────────────

function BookIcon() {
  return (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
      <path strokeLinecap="square" d="M4 19.5A2.5 2.5 0 016.5 17H20" />
      <path strokeLinecap="square" d="M6.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15A2.5 2.5 0 016.5 2z" />
    </svg>
  );
}

function PageIcon() {
  return (
    <svg className="w-6 h-6 text-ink-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <path strokeLinecap="square" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414A1 1 0 0121 9.414V19a2 2 0 01-2 2z" />
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
      <path strokeLinecap="square" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
    </svg>
  );
}
