import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

// US Letter dimensions in points (72 pts = 1 inch)
const PAGE_WIDTH = 612;   // 8.5 inches
const PAGE_HEIGHT = 792;  // 11 inches

// Margins (in points)
const MARGIN = 36; // 0.5 inch

/**
 * Build a coloring-book PDF from an array of PNG image Buffers.
 *
 * @param {Buffer[]} imageBuffers  - One PNG buffer per coloring page
 * @param {string}   topic         - Used in document metadata
 * @returns {Promise<Uint8Array>}  - Raw PDF bytes
 */
export async function buildColoringBookPDF(imageBuffers, topic) {
  const pdfDoc = await PDFDocument.create();

  // Document metadata
  pdfDoc.setTitle(`${topic} Coloring Book — BookMint AI`);
  pdfDoc.setAuthor('BookMint AI (bookmintai.ca)');
  pdfDoc.setSubject('AI-Generated Coloring Book');
  pdfDoc.setKeywords(['coloring book', 'printable', topic, 'BookMint AI']);
  pdfDoc.setCreator('BookMint AI');
  pdfDoc.setProducer('BookMint AI — bookmintai.ca');
  pdfDoc.setCreationDate(new Date());
  pdfDoc.setModificationDate(new Date());

  // --- Cover Page ---
  const coverPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  await addCoverPage(pdfDoc, coverPage, topic, imageBuffers.length);

  // --- Content Pages ---
  for (let i = 0; i < imageBuffers.length; i++) {
    const page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    await addColoringPage(pdfDoc, page, imageBuffers[i], i + 1, imageBuffers.length, topic);
  }

  // --- Back Cover ---
  const backPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  addBackCover(backPage);

  const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
  return pdfBytes;
}

/**
 * Add a styled cover page.
 */
async function addCoverPage(pdfDoc, page, topic, pageCount) {
  const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontLight = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const { width, height } = page.getSize();

  // Background — off-white
  page.drawRectangle({
    x: 0, y: 0,
    width, height,
    color: rgb(0.98, 0.97, 0.95),
  });

  // Top decorative bar
  page.drawRectangle({
    x: 0, y: height - 8,
    width, height: 8,
    color: rgb(0.77, 0.38, 0.18), // rust
  });

  // Bottom decorative bar
  page.drawRectangle({
    x: 0, y: 0,
    width, height: 8,
    color: rgb(0.77, 0.38, 0.18),
  });

  // Left border
  page.drawRectangle({
    x: 0, y: 0,
    width: 8, height,
    color: rgb(0.77, 0.38, 0.18),
  });

  // Right border
  page.drawRectangle({
    x: width - 8, y: 0,
    width: 8, height,
    color: rgb(0.77, 0.38, 0.18),
  });

  // Inner border line
  page.drawRectangle({
    x: 20, y: 20,
    width: width - 40, height: height - 40,
    borderColor: rgb(0.77, 0.38, 0.18),
    borderWidth: 1,
    color: rgb(0, 0, 0, 0), // transparent fill
    opacity: 0,
    borderOpacity: 0.3,
  });

  // "COLORING BOOK" label
  const labelText = 'COLORING BOOK';
  const labelSize = 11;
  const labelWidth = font.widthOfTextAtSize(labelText, labelSize);
  page.drawText(labelText, {
    x: (width - labelWidth) / 2,
    y: height - 80,
    size: labelSize,
    font,
    color: rgb(0.77, 0.38, 0.18),
    characterSpacing: 4,
  });

  // Decorative line under label
  page.drawLine({
    start: { x: width / 2 - 60, y: height - 95 },
    end:   { x: width / 2 + 60, y: height - 95 },
    thickness: 1,
    color: rgb(0.77, 0.38, 0.18),
    opacity: 0.5,
  });

  // Main title (topic, capitalized)
  const titleText = capitalize(topic);
  const titleSize = clampFontSize(font, titleText, width - 100, 48);
  const titleWidth = font.widthOfTextAtSize(titleText, titleSize);
  page.drawText(titleText, {
    x: (width - titleWidth) / 2,
    y: height / 2 + 30,
    size: titleSize,
    font,
    color: rgb(0.16, 0.13, 0.1),
  });

  // Subtitle
  const sub = `${pageCount} Pages to Color`;
  const subSize = 14;
  const subWidth = fontLight.widthOfTextAtSize(sub, subSize);
  page.drawText(sub, {
    x: (width - subWidth) / 2,
    y: height / 2 - 20,
    size: subSize,
    font: fontLight,
    color: rgb(0.5, 0.45, 0.38),
  });

  // BookMint AI branding
  const brand = 'Generated by BookMint AI  ·  bookmintai.ca';
  const brandSize = 9;
  const brandWidth = fontLight.widthOfTextAtSize(brand, brandSize);
  page.drawText(brand, {
    x: (width - brandWidth) / 2,
    y: 50,
    size: brandSize,
    font: fontLight,
    color: rgb(0.6, 0.55, 0.48),
  });

  // Decorative diamond ornament
  drawDiamond(page, width / 2, height / 2 + 130, 6, rgb(0.77, 0.38, 0.18));
  drawDiamond(page, width / 2 - 20, height / 2 + 130, 3, rgb(0.77, 0.38, 0.18));
  drawDiamond(page, width / 2 + 20, height / 2 + 130, 3, rgb(0.77, 0.38, 0.18));
}

/**
 * Embed a coloring page image on a PDF page.
 */
async function addColoringPage(pdfDoc, page, imageBuffer, pageNum, total, topic) {
  const { width, height } = page.getSize();

  // White background
  page.drawRectangle({
    x: 0, y: 0,
    width, height,
    color: rgb(1, 1, 1),
  });

  // Embed the PNG image
  let pngImage;
  try {
    pngImage = await pdfDoc.embedPng(imageBuffer);
  } catch (e) {
    // If PNG embedding fails try JPEG fallback
    pngImage = await pdfDoc.embedJpg(imageBuffer);
  }

  // Image area (full page with margins)
  const imgAreaX = MARGIN;
  const imgAreaY = MARGIN + 20; // extra bottom for footer
  const imgAreaW = width - MARGIN * 2;
  const imgAreaH = height - MARGIN * 2 - 20;

  // Scale image to fill area while maintaining aspect ratio
  const imgDims = pngImage.scaleToFit(imgAreaW, imgAreaH);

  // Centre the image in the available area
  const imgX = imgAreaX + (imgAreaW - imgDims.width) / 2;
  const imgY = imgAreaY + (imgAreaH - imgDims.height) / 2;

  page.drawImage(pngImage, {
    x: imgX,
    y: imgY,
    width: imgDims.width,
    height: imgDims.height,
  });

  // Thin footer
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const footerText = `Page ${pageNum} of ${total}  ·  ${capitalize(topic)} Coloring Book  ·  bookmintai.ca`;
  const footerSize = 7;
  const footerWidth = font.widthOfTextAtSize(footerText, footerSize);
  page.drawText(footerText, {
    x: (width - footerWidth) / 2,
    y: 16,
    size: footerSize,
    font,
    color: rgb(0.7, 0.65, 0.58),
  });
}

/**
 * Simple back-cover page.
 */
function addBackCover(page) {
  const { width, height } = page.getSize();

  page.drawRectangle({
    x: 0, y: 0, width, height,
    color: rgb(0.16, 0.13, 0.1),
  });

  // Decorative rust bar at top
  page.drawRectangle({
    x: 0, y: height - 6, width, height: 6,
    color: rgb(0.77, 0.38, 0.18),
  });

  // We can't embed a Google Font at runtime in pdf-lib, so we use the
  // built-in Helvetica family for the back cover too.
  // (Decorative text is drawn with drawText calls below once font is embedded –
  //  but addBackCover is synchronous, so we skip font embed here and just
  //  draw rectangles / lines for the design.)

  // Simple centered ornament – three stacked lines
  const cx = width / 2;
  const cy = height / 2;
  page.drawLine({ start: { x: cx - 40, y: cy + 10 }, end: { x: cx + 40, y: cy + 10 }, thickness: 2, color: rgb(0.77, 0.38, 0.18) });
  page.drawLine({ start: { x: cx - 25, y: cy      }, end: { x: cx + 25, y: cy      }, thickness: 1, color: rgb(0.77, 0.38, 0.18), opacity: 0.6 });
  page.drawLine({ start: { x: cx - 40, y: cy - 10 }, end: { x: cx + 40, y: cy - 10 }, thickness: 2, color: rgb(0.77, 0.38, 0.18) });
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function capitalize(str) {
  return str
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Reduce font size until the text fits within maxWidth.
 */
function clampFontSize(font, text, maxWidth, startSize) {
  let size = startSize;
  while (size > 12 && font.widthOfTextAtSize(text, size) > maxWidth) {
    size -= 2;
  }
  return size;
}

function drawDiamond(page, cx, cy, r, color) {
  page.drawLine({ start: { x: cx,   y: cy + r }, end: { x: cx + r, y: cy     }, thickness: 1, color });
  page.drawLine({ start: { x: cx + r, y: cy   }, end: { x: cx,     y: cy - r }, thickness: 1, color });
  page.drawLine({ start: { x: cx,   y: cy - r }, end: { x: cx - r, y: cy     }, thickness: 1, color });
  page.drawLine({ start: { x: cx - r, y: cy   }, end: { x: cx,     y: cy + r }, thickness: 1, color });
}
